accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/',
         auth_views.LoginView.as_view(
             template_name='registration/login.html',
             extra_context={'title': 'Log in'}
         ),
         name='login'),
    path('logout/',
         auth_views.LogoutView.as_view(
             template_name='registration/logout.html'
         ),
         name='logout'),
    path('registration/',
         views.RegistrationFormView.as_view(
             extra_context={'title': 'Sign in'}
         ),
         name='registration'),
    path('registration/done/',
         views.RegistrationSuccessView.as_view()),
    path('<int:pk>/',
         views.UserProfileView.as_view(),
         name='user-profile'),
    path('my/',
         views.CurrentUserProfileView.as_view(),
         name='current-user'),
    path('', RedirectView.as_view(pattern_name='accounts:login'), name='home'),
]

noticeboard/urls.py
from django.urls import path
from . import views

app_name = 'noticeboard'
urlpatterns = [
    path('', views.ActiveNoticesView.as_view(), name='active-notices'),
    path('expired/', views.ExpiredNoticeView.as_view(), name='expired-notices'),
    path('<int:pk>/', views.SingleNoticeView.as_view(), name='single-notice'),
    path('new/', views.NewNoticeView.as_view(), name='new'),
    path('<int:pk>/delete', views.DeleteNoticeView.as_view(), name='delete'),
    path('<int:pk>/update', views.UpdateNoticeView.as_view(), name='update')
]

project_x/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

"""project_x URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='noticeboard:active-notices'), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('noticeboard/', include('noticeboard.urls', namespace='noticeboard')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models

# Create your models here.

noticeboard/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.


class Notice(models.Model):
    def __str__(self):
        return self.title

    title = models.CharField(max_length=40)
    pub_date = models.DateTimeField('Date published', auto_now_add=True)
    exp_date = models.DateTimeField('Expiration date')
    body = models.TextField(max_length=500)
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, max_length=1)
    # hidden = models.BooleanField(default=False)
    # attachment = models.FileField(blank=True)

    def get_absolute_url(self):
        return reverse('noticeboard:single-notice', kwargs={'pk': self.pk})

    def has_expired(self):
        return self.exp_date <= timezone.now()

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class UserCreationExtendedForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

noticeboard/forms.py
from django import forms
from .models import Notice
from django.utils import timezone


class NewNoteForm(forms.ModelForm):
    class Meta:
        model = Notice
        fields = ['title', 'body', 'exp_date']
        widgets = {
            'exp_date': forms.DateInput(attrs={'type': 'date'}),
            'body': forms.Textarea,
        }

    def clean(self):
        cleaned_data = super().clean()
        exp_date = cleaned_data.get("exp_date")

        if exp_date <= timezone.now():
            msg = "Expiration date must be in the future."
            self.add_error('exp_date', msg)

accounts/views.py
from django.shortcuts import render, get_object_or_404
from .forms import UserCreationExtendedForm
from django.views.generic.edit import FormView
from django.views.generic.base import TemplateView
from django.views.generic import DetailView
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from noticeboard.models import Notice


# Create your views here.
class RegistrationFormView(FormView):
    form_class = UserCreationExtendedForm
    template_name = 'registration/registration.html'
    success_url = 'done/'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class RegistrationSuccessView(TemplateView):
    template_name = 'registration/registration-success.html'


class UserProfileView(LoginRequiredMixin, DetailView):
    model = User

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["notices"] = Notice.objects.filter(
            author=self.object).order_by('-exp_date')
        return context


class CurrentUserProfileView(UserProfileView):
    success_url = reverse_lazy('noticeboard:active-notices')

    def get_success_url(self):
        return reverse_lazy('noticeboard:active-notices')

    def get_object(self):
        return get_object_or_404(User, pk=self.request.user.id)

noticeboard/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .mixins import UserIsAuthorOrStaffMixin
from .models import Notice
from .forms import NewNoteForm
from django.urls import reverse_lazy
from django.utils import timezone


# Create your views here.


class ActiveNoticesView(generic.ListView):
    def get_queryset(self):
        """Return only the notices which have not expired yet"""
        return Notice.objects.filter(exp_date__gt=timezone.now()).order_by('exp_date', 'title')
    model = Notice
    extra_context = {
        'title': 'Active Notices'
    }


class ExpiredNoticeView(LoginRequiredMixin, generic.ListView):
    def get_queryset(self):
        """Return only the notices which have expired"""
        return Notice.objects.filter(exp_date__lte=timezone.now()).order_by('-exp_date', 'title')
    model = Notice
    extra_context = {
        'title': 'Expired Notices'
    }


class SingleNoticeView(generic.DetailView):
    model = Notice


class NewNoticeView(LoginRequiredMixin, generic.CreateView):
    form_class = NewNoteForm
    template_name = 'noticeboard/notice_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class DeleteNoticeView(LoginRequiredMixin, UserIsAuthorOrStaffMixin, generic.DeleteView):
    model = Notice
    success_url = reverse_lazy('noticeboard:active-notices')


class UpdateNoticeView(LoginRequiredMixin, UserIsAuthorOrStaffMixin, generic.UpdateView):
    form_class = NewNoteForm
    model = Notice
    template_name = 'noticeboard/notice_form.html'

noticeboard/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {# <link rel="stylesheet" href="style.css"> #}
    <title>{% block title %}Noticeboard{% endblock %}</title>
</head>

<body>
    <div id="sidebar">
        {% block sidebar %}
        <ul>
            {% url 'accounts:login' as login_url %}

            {% if request.path != login_url %}

            {% if not request.user.is_authenticated %}
            <li><a href="{% url 'accounts:login' %}">Log in</a></li>
            {% else %}
            <li>
                <p>Hello, <a href={% url 'accounts:current-user' %}>
                        {{request.user.username}}</a>. <a href="{% url 'accounts:logout' %}">Log out?</a></p>
            </li>
            {% endif %}

            {% endif %}

            <li><a href="{% url 'noticeboard:active-notices' %}">Active notices</a></li>
            <li><a href="{% url 'noticeboard:expired-notices' %}">Expired notices</a></li>
            <li><a href="{% url 'noticeboard:new' %}">Publish a new notice</a></li>
        </ul>
        {% endblock %}
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>

</html>

noticeboard/templates/noticeboard/notice_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

noticeboard/templates/noticeboard/notice_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ object.title }}</h1>
<p>{{ object.body }}</p>
<p>Published: {{ object.pub_date|date }}</p>
<p>Expires: {{ object.exp_date|date }}</p>
<p>Author:
    {% if object.author is not None%}
    <a href={% url 'accounts:user-profile' pk=object.author.pk %}>{{ object.author }}</a>
    {% else %}
    {{ object.author}}
    {% endif %}
</p>

{% if request.user == object.author or request.user.is_staff %}
<h2>Actions</h2>
<ul>
    <li>
        <a href={% url 'noticeboard:delete' pk=object.pk %}>Delete notice</a>
    </li>
    <li>
        <a href={% url 'noticeboard:update' pk=object.pk %}>Update notice</a>
    </li>
</ul>
{% endif %}

{% endblock %}

noticeboard/templates/noticeboard/notice_form.html
{% extends 'base.html' %}

{% block content %}

<form method="POST" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="Submit" value='Submit' />
</form>

{% endblock %}

noticeboard/templates/noticeboard/notice_list.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ title }}</h1>
<ul>
    {% for notice in object_list %}
    <li><a href="{% url 'noticeboard:single-notice' notice.id %}">
            {{ notice.title }} - Expiration date: {{ notice.exp_date|date }}</a></li>
    {% empty %}
    <li>No notices yet.</li>
    {% endfor %}
</ul>
{% endblock %}